# How to run matlab files from python script

- First, we need to install the MATLAB API for Python. On Windows, this can be done by following these steps:
  - open task manager
  - click on "Run new task"
  - check on "Create this task with adminsitrative privileges" and open cmd
  - Type: `cd "matlabroot/extern/engines/python"`, where matlabroot is the folder in which matlab is installed
    - To know matlabroot, type matlabroot in the command window on Matlab
  - type `python -m pip install setuptools`

- Next we need to install the Matlab library in the current environment
  - This has been already installed in the maximin2 environment in the Github repo, so, once it is downloaded:
    - activate the environment by typing `conda activate path/.conda`
    - path is the address of the folder of the local repo, i.e. the folder where the repo was downloaded to
    - you can get by right clicking on the maximin2 folder from the left panel
  - Instead of downloading the repo, you may just run `python -m pip install matlabengine==9.13.7` in the VSCode terminal
    - Note that you need at most python 3.10. The current version 3.11 is not yet incorporated in the library
    - To downgrade to python 3.11, the easiest thing is to create a conda environment
      - This is done by typing `conda create --name nenv python=3.10`, where
        - `nenv` is the name of the new environment
        - the new environment will need to be activated anytime you want to use matlab from python
        - this can be done by typing `conda activate nenv` from the terminal
    - Any MATLAB file in the folder open in VScode may then be run

- Once the library is installed, MATLAB functions in the repo/local folder may be executed as shown below

In [2]:
import numpy as np
import matlab.engine

ModuleNotFoundError: No module named 'matlab.engine'; 'matlab' is not a package

First, we start MATLAB's engine

In [2]:
eng = matlab.engine.start_matlab()

MATLAB built-in functions may be called as methods of the `eng` class

In [3]:
print(eng.sqrt(4.0))

2.0


Most importantly, any MATLAB function may be called as follows

In [4]:
base = np.asarray([1.0,2.0,3.0,4.0])
exp = 2.0
ret = eng.pow_fun(matlab.double(base.tolist()),exp)
print(ret)

[[1.0,4.0,9.0,16.0]]


Similarly, one may run a MATLAB script

In [5]:
eng.BGDataReader(nargout = 0)

In [6]:
from scipy.io import loadmat
import pandas as pd

mat = loadmat('bgset512.mat')
# mdata = mat['bgset512']  # variable in mat file
# mdtype = mdata.dtype  # dtypes of structures are "unsized objects"
# # * SciPy reads in structures as structured NumPy arrays of dtype object
# # * The size of the array is the size of the structure array, not the number
# #   elements in any particular field. The shape defaults to 2-dimensional.
# # * For convenience make a dictionary of the data using the names from dtypes
# # * Since the structure has only one element, but is 2-D, index it at [0, 0]
# ndata = {n: mdata[n][0, 0] for n in mdtype.names}
# # Reconstruct the columns of the data table from just the time series
# # Use the number of intervals to test if a field is a column or metadata
# columns = [n for n, v in ndata.iteritems() if v.size == ndata['numIntervals']]
# # now make a data frame, setting the time stamps as the index
# df = pd.DataFrame(np.concatenate([ndata[c] for c in columns], axis=1),
#                   index=[datetime(*ts) for ts in ndata['timestamps']],
#                   columns=columns)


In [7]:
print(mat['A'])

[[2.45063341e-02 1.31611686e+00 2.04586651e-02 1.53441623e+00]
 [4.33527127e-02 1.18987791e+00 3.88250476e-02 1.34694989e+00]
 [1.41905958e-02 1.00223248e+00 1.25380244e-02 1.03215805e+00]
 ...
 [3.14164844e-03 8.11613539e+00 6.99157050e-03 3.67615533e+00]
 [4.79012877e-03 1.10149370e+01 4.66656371e-03 1.10163677e+01]
 [3.10749134e-03 1.23883174e+00 3.19196827e-03 6.69163048e-01]]
